--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/FurkanYks/VanillaFishing
build-by-default: true
branches:
- main
projects:
  VanillaFishing:
    path: ""
    icon: "resources/icon.png"
...
